const express = require('express');

const githubController = require('../controllers/github.controller');
const authMiddleware = require('../middlewares/auth.middleware');

const router = express.Router();
const attachFullNameRepoId = (req, res, next) => {
  req.params.repoId = `${req.params.owner}/${req.params.repo}`;
  return next();
};

/**
 * @swagger
 * tags:
 *   - name: GitHub
 *     description: GitHub OAuth and repository APIs
 */

/**
 * @swagger
 * /api/github/oauth:
 *   get:
 *     tags: [GitHub]
 *     summary: Start GitHub repository connect OAuth flow
 *     description: Generates a GitHub OAuth authorization URL for connecting the current authenticated user's GitHub account for repository access. The callback is shared-capable and dispatches by saved OAuth state.
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: query
 *         name: redirectUrl
 *         required: false
 *         schema:
 *           type: string
 *           example: gitanalyzer://github/connect
 *         description: Optional allowlisted frontend connect callback. Web can use http://localhost:5173/github/connect; mobile must use the exact MOBILE_REDIRECT_URL such as gitanalyzer://github/connect. Defaults to FRONTEND_URL /github/connect.
 *       - in: query
 *         name: forceAccountSelection
 *         required: false
 *         schema:
 *           type: boolean
 *           example: true
 *         description: Optional FE hint for reconnect UX. GitHub OAuth may still reuse the active github.com browser session; backend cannot clear GitHub cookies.
 *     responses:
 *       200:
 *         description: OAuth URL generated successfully
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success:
 *                   type: boolean
 *                   example: true
 *                 message:
 *                   type: string
 *                   example: GitHub OAuth URL generated successfully
 *                 data:
 *                   type: object
 *                   properties:
 *                     authorizeUrl:
 *                       type: string
 *                       example: https://github.com/login/oauth/authorize?client_id=xxx&redirect_uri=http%3A%2F%2Flocalhost%3A5000%2Fapi%2Fgithub%2Foauth%2Fcallback&scope=repo+read%3Auser+user%3Aemail&state=abc
 *                     forceAccountSelection:
 *                       type: boolean
 *                       example: true
 *       401:
 *         description: Unauthorized
 *       500:
 *         description: GitHub OAuth environment is not configured
 */
router.get('/oauth', authMiddleware, githubController.startOAuth);

/**
 * @swagger
 * /api/github/connect:
 *   get:
 *     tags: [GitHub]
 *     summary: Start GitHub repository connect OAuth flow
 *     description: Alias of /api/github/oauth for FE reconnect flows. Accepts forceAccountSelection=true as a UX hint only; backend cannot log the user out of github.com or force account switching.
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: query
 *         name: redirectUrl
 *         required: false
 *         schema:
 *           type: string
 *           example: http://localhost:5173/github/connect
 *       - in: query
 *         name: forceAccountSelection
 *         required: false
 *         schema:
 *           type: boolean
 *           example: true
 *     responses:
 *       200:
 *         description: OAuth URL generated successfully
 *       401:
 *         description: Unauthorized
 *       500:
 *         description: GitHub OAuth environment is not configured
 */
router.get('/connect', authMiddleware, githubController.startOAuth);

/**
 * @swagger
 * /api/github/oauth/callback:
 *   get:
 *     tags: [GitHub]
 *     summary: Handle shared GitHub OAuth callback
 *     description: Handles GitHub OAuth callbacks for both Login with GitHub and repository connect. The backend first checks whether state belongs to the login flow; if so, it creates an app JWT and redirects to the saved /auth/github/callback URL with the JWT in the URL fragment. Otherwise it handles the connect flow and redirects to the saved /github/connect URL.
 *     security: []
 *     parameters:
 *       - in: query
 *         name: code
 *         required: true
 *         schema:
 *           type: string
 *         description: Authorization code returned by GitHub
 *       - in: query
 *         name: state
 *         required: true
 *         schema:
 *           type: string
 *         description: CSRF protection state generated by the backend. Login states are stored separately from connect states.
 *       - in: query
 *         name: error
 *         required: false
 *         schema:
 *           type: string
 *         description: OAuth error returned by GitHub when authorization fails
 *     responses:
 *       302:
 *         description: For login, redirects to /auth/github/callback#success=true&accessToken=<JWT>&provider=github. For connect, redirects to /github/connect. Errors are returned in the frontend callback query string.
 *       400:
 *         description: Missing, invalid, expired, or already-used OAuth state
 *       500:
 *         description: GitHub OAuth environment or server dependencies are not configured
 */
router.get('/oauth/callback', githubController.handleOAuthCallback);

/**
 * @swagger
 * /api/github/me:
 *   get:
 *     tags: [GitHub]
 *     summary: Get connected GitHub account legacy alias
 *     description: Legacy alias of GET /api/github/account.
 *     security:
 *       - bearerAuth: []
 *     responses:
 *       200:
 *         description: GitHub account retrieved successfully
 *       401:
 *         description: Unauthorized
 */
router.get('/me', authMiddleware, githubController.getMe);

/**
 * @swagger
 * /api/github/account:
 *   get:
 *     tags: [GitHub]
 *     summary: Get current connected GitHub account
 *     description: Returns the current user's connected GitHub account status. The response never includes the GitHub access token.
 *     security:
 *       - bearerAuth: []
 *     responses:
 *       200:
 *         description: GitHub account fetched successfully
 *         content:
 *           application/json:
 *             examples:
 *               connected:
 *                 value:
 *                   success: true
 *                   message: GitHub account fetched successfully
 *                   data:
 *                     connected: true
 *                     account:
 *                       githubUserId: "123456"
 *                       username: octocat
 *                       displayName: The Octocat
 *                       avatarUrl: https://avatars.githubusercontent.com/u/123456?v=4
 *                       email: octocat@example.com
 *                       connectedAt: "2026-07-14T00:00:00.000Z"
 *                       updatedAt: "2026-07-14T00:00:00.000Z"
 *                   errorCode: null
 *               disconnected:
 *                 value:
 *                   success: true
 *                   message: GitHub account fetched successfully
 *                   data:
 *                     connected: false
 *                     account: null
 *                   errorCode: null
 *       401:
 *         description: Unauthorized
 */
router.get('/account', authMiddleware, githubController.getAccount);

/**
 * @swagger
 * /api/github/disconnect:
 *   delete:
 *     tags: [GitHub]
 *     summary: Disconnect current GitHub account legacy alias
 *     description: Legacy alias of DELETE /api/github/account.
 *     security:
 *       - bearerAuth: []
 *     responses:
 *       200:
 *         description: GitHub account disconnected successfully
 *       401:
 *         description: Unauthorized
 */
router.delete('/disconnect', authMiddleware, githubController.disconnect);

/**
 * @swagger
 * /api/github/account:
 *   delete:
 *     tags: [GitHub]
 *     summary: Disconnect current GitHub account
 *     description: Unlinks the current user's GitHub account from this app and removes the stored local access token. It does not delete repositories, analysis results, roadmaps, chat, feedback, or log the browser out of github.com.
 *     security:
 *       - bearerAuth: []
 *     responses:
 *       200:
 *         description: GitHub account disconnected successfully
 *         content:
 *           application/json:
 *             example:
 *               success: true
 *               message: GitHub account disconnected successfully
 *               data:
 *                 connected: false
 *                 githubLogoutUrl: https://github.com/logout
 *                 note: Disconnected from this app. To connect a different GitHub account, log out from GitHub.com or use an incognito window before reconnecting.
 *               errorCode: null
 *       401:
 *         description: Unauthorized
 */
router.delete('/account', authMiddleware, githubController.disconnect);

/**
 * @swagger
 * /api/github/repositories:
 *   get:
 *     tags: [GitHub]
 *     summary: Fetch repositories from GitHub and sync to database
 *     security:
 *       - bearerAuth: []
 *     responses:
 *       200:
 *         description: Repositories fetched successfully
 *       401:
 *         description: Unauthorized
 */
router.get('/repositories', authMiddleware, githubController.getRepositories);

/**
 * @swagger
 * /api/github/repositories/cached:
 *   get:
 *     tags: [GitHub]
 *     summary: Get cached repositories from database
 *     security:
 *       - bearerAuth: []
 *     responses:
 *       200:
 *         description: Cached repositories fetched successfully
 *       401:
 *         description: Unauthorized
 */
router.get('/repositories/cached', authMiddleware, githubController.getCachedRepositories);
// package/config endpoints (cached before live)

/**
 * @swagger
 * /api/github/repositories/{repoId}/packages/cached:
 *   get:
 *     tags: [GitHub]
 *     summary: Get cached package and config files for a repository
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: path
 *         name: repoId
 *         required: true
 *         schema:
 *           type: string
 *         description: Repository MongoDB _id or GitHub repo id
 *     responses:
 *       200:
 *         description: Cached packages fetched successfully
 *       401:
 *         description: Unauthorized
 *       404:
 *         description: Repository not found
 */
router.get('/repositories/:owner/:repo/packages/cached', authMiddleware, attachFullNameRepoId, githubController.getCachedPackages);
router.get('/repositories/:repoId/packages/cached', authMiddleware, githubController.getCachedPackages);

/**
 * @swagger
 * /api/github/repositories/{repoId}/packages:
 *   get:
 *     tags: [GitHub]
 *     summary: Fetch package and config files for a repository
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: path
 *         name: repoId
 *         required: true
 *         schema:
 *           type: string
 *         description: Repository MongoDB _id or GitHub repo id
 *     responses:
 *       200:
 *         description: Packages fetched successfully
 *       401:
 *         description: Unauthorized
 *       404:
 *         description: Repository not found
 */
router.get('/repositories/:owner/:repo/packages', authMiddleware, attachFullNameRepoId, githubController.getPackages);
router.get('/repositories/:repoId/packages', authMiddleware, githubController.getPackages);
// commits endpoints (cached before live)

/**
 * @swagger
 * /api/github/repositories/{repoId}/commits/cached:
 *   get:
 *     tags: [GitHub]
 *     summary: Get cached commit history for a repository
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: path
 *         name: repoId
 *         required: true
 *         schema:
 *           type: string
 *         description: Repository MongoDB _id or GitHub repo id
 *     responses:
 *       200:
 *         description: Cached commits fetched successfully
 *       401:
 *         description: Unauthorized
 *       404:
 *         description: Repository not found
 */
router.get('/repositories/:owner/:repo/commits/cached', authMiddleware, attachFullNameRepoId, githubController.getCachedCommits);
router.get('/repositories/:repoId/commits/cached', authMiddleware, githubController.getCachedCommits);

/**
 * @swagger
 * /api/github/repositories/{repoId}/commits:
 *   get:
 *     tags: [GitHub]
 *     summary: Fetch commit history for a repository
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: path
 *         name: repoId
 *         required: true
 *         schema:
 *           type: string
 *         description: Repository MongoDB _id or GitHub repo id
 *     responses:
 *       200:
 *         description: Commits fetched successfully
 *       401:
 *         description: Unauthorized
 *       404:
 *         description: Repository not found
 */
router.get('/repositories/:owner/:repo/commits', authMiddleware, attachFullNameRepoId, githubController.getCommits);
router.get('/repositories/:repoId/commits', authMiddleware, githubController.getCommits);

/**
 * @swagger
 * /api/github/repositories/{repoId}:
 *   get:
 *     tags: [GitHub]
 *     summary: Get repository details by repo id
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: path
 *         name: repoId
 *         required: true
 *         schema:
 *           type: string
 *         description: Repository MongoDB _id or GitHub repo id
 *     responses:
 *       200:
 *         description: Repository fetched successfully
 *       401:
 *         description: Unauthorized
 *       404:
 *         description: Repository not found
 */
router.get('/repositories/:owner/:repo', authMiddleware, attachFullNameRepoId, githubController.getRepositoryById);
router.get('/repositories/:repoId', authMiddleware, githubController.getRepositoryById);

module.exports = router;
