// Curated LearningResource catalog.
// Developers can add curated videos here. When resources/search is called and
// MongoDB has no matching resource, the system checks this catalog before YouTube.
// Matching catalog items are cached into MongoDB as source = "curated".
module.exports = [
  {
    skillName: 'HTML',
    targetRole: 'Frontend Developer',
    level: 'beginner',
    language: 'en',
    type: 'video',
    title: 'HTML Tutorial for Beginners',
    url: 'https://www.youtube.com/watch?v=UB1O30fR-EE',
    provider: 'YouTube',
    tags: ['html', 'frontend', 'web'],
    source: 'curated',
    score: 95,
  },
  {
    skillName: 'CSS',
    targetRole: 'Frontend Developer',
    level: 'beginner',
    language: 'en',
    type: 'video',
    title: 'CSS Tutorial for Beginners',
    url: 'https://www.youtube.com/watch?v=yfoY53QXEnI',
    provider: 'YouTube',
    tags: ['css', 'frontend', 'web'],
    source: 'curated',
    score: 94,
  },
  {
    skillName: 'JavaScript',
    targetRole: 'Software Developer',
    level: 'beginner',
    language: 'en',
    type: 'video',
    title: 'JavaScript Tutorial for Beginners',
    url: 'https://www.youtube.com/watch?v=W6NZfCO5SIk',
    provider: 'YouTube',
    tags: ['javascript', 'frontend', 'web'],
    source: 'curated',
    score: 95,
  },
  {
    skillName: 'React',
    targetRole: 'Frontend Developer',
    level: 'beginner',
    language: 'en',
    type: 'video',
    title: 'React Tutorial for Beginners',
    url: 'https://www.youtube.com/watch?v=SqcY0GlETPk',
    provider: 'YouTube',
    tags: ['react', 'frontend', 'component'],
    source: 'curated',
    score: 94,
  },
  {
    skillName: 'Node.js',
    targetRole: 'Backend Developer',
    level: 'beginner',
    language: 'en',
    type: 'video',
    title: 'Node.js Tutorial for Beginners',
    url: 'https://www.youtube.com/watch?v=TlB_eWDSMt4',
    provider: 'YouTube',
    tags: ['node.js', 'backend', 'javascript'],
    source: 'curated',
    score: 94,
  },
  {
    skillName: 'Express.js',
    targetRole: 'Backend Developer',
    level: 'beginner',
    language: 'en',
    type: 'video',
    title: 'Express.js Tutorial for Beginners',
    url: 'https://www.youtube.com/watch?v=L72fhGm1tfE',
    provider: 'YouTube',
    tags: ['express.js', 'backend', 'api'],
    source: 'curated',
    score: 92,
  },
  {
    skillName: 'MongoDB',
    targetRole: 'Backend Developer',
    level: 'beginner',
    language: 'en',
    type: 'video',
    title: 'MongoDB Tutorial for Beginners',
    url: 'https://www.youtube.com/watch?v=ofme2o29ngU',
    provider: 'YouTube',
    tags: ['mongodb', 'database', 'backend'],
    source: 'curated',
    score: 92,
  },
  {
    skillName: 'Git',
    targetRole: 'Software Developer',
    level: 'beginner',
    language: 'en',
    type: 'video',
    title: 'Git Tutorial for Beginners',
    url: 'https://www.youtube.com/watch?v=8JJ101D3knE',
    provider: 'YouTube',
    tags: ['git', 'version-control', 'github'],
    source: 'curated',
    score: 93,
  },
  {
    skillName: 'Docker',
    targetRole: 'Software Developer',
    level: 'beginner',
    language: 'en',
    type: 'video',
    title: 'Docker Tutorial for Beginners',
    url: 'https://www.youtube.com/watch?v=fqMOX6JJhGo',
    provider: 'YouTube',
    tags: ['docker', 'deployment', 'devops'],
    source: 'curated',
    score: 93,
  },
  {
    skillName: 'HTML',
    targetRole: 'Frontend Developer',
    level: 'intermediate',
    language: 'en',
    type: 'video',
    title: 'HTML Semantic Forms and Accessibility Tutorial',
    url: 'TODO_HTML_INTERMEDIATE_VIDEO_URL',
    provider: 'YouTube',
    tags: ['html', 'semantic-html', 'forms', 'accessibility'],
    source: 'curated',
    score: 90,
  },
  {
    skillName: 'CSS',
    targetRole: 'Frontend Developer',
    level: 'intermediate',
    language: 'en',
    type: 'video',
    title: 'CSS Flexbox Grid and Responsive Layout Tutorial',
    url: 'TODO_CSS_INTERMEDIATE_VIDEO_URL',
    provider: 'YouTube',
    tags: ['css', 'flexbox', 'grid', 'responsive'],
    source: 'curated',
    score: 90,
  },
  {
    skillName: 'JavaScript',
    targetRole: 'Software Developer',
    level: 'intermediate',
    language: 'en',
    type: 'video',
    title: 'JavaScript Async Await and DOM Tutorial',
    url: 'TODO_JAVASCRIPT_INTERMEDIATE_VIDEO_URL',
    provider: 'YouTube',
    tags: ['javascript', 'async-await', 'dom', 'frontend'],
    source: 'curated',
    score: 91,
  },
  {
    skillName: 'React',
    targetRole: 'Frontend Developer',
    level: 'intermediate',
    language: 'en',
    type: 'video',
    title: 'React Hooks Router and API Integration Tutorial',
    url: 'TODO_REACT_INTERMEDIATE_VIDEO_URL',
    provider: 'YouTube',
    tags: ['react', 'hooks', 'router', 'api'],
    source: 'curated',
    score: 91,
  },
  {
    skillName: 'Node.js',
    targetRole: 'Backend Developer',
    level: 'intermediate',
    language: 'en',
    type: 'video',
    title: 'Node.js Environment Variables and Async Patterns Tutorial',
    url: 'TODO_NODE_JS_INTERMEDIATE_VIDEO_URL',
    provider: 'YouTube',
    tags: ['node.js', 'backend', 'async', 'environment-variables'],
    source: 'curated',
    score: 90,
  },
  {
    skillName: 'Express.js',
    targetRole: 'Backend Developer',
    level: 'intermediate',
    language: 'en',
    type: 'video',
    title: 'Express.js Middleware Validation and Authentication Tutorial',
    url: 'TODO_EXPRESS_JS_INTERMEDIATE_VIDEO_URL',
    provider: 'YouTube',
    tags: ['express.js', 'middleware', 'validation', 'authentication'],
    source: 'curated',
    score: 90,
  },
  {
    skillName: 'MongoDB',
    targetRole: 'Backend Developer',
    level: 'intermediate',
    language: 'en',
    type: 'video',
    title: 'MongoDB Aggregation Indexes and Schema Design Tutorial',
    url: 'TODO_MONGODB_INTERMEDIATE_VIDEO_URL',
    provider: 'YouTube',
    tags: ['mongodb', 'aggregation', 'indexes', 'database'],
    source: 'curated',
    score: 90,
  },
  {
    skillName: 'Git',
    targetRole: 'Software Developer',
    level: 'intermediate',
    language: 'en',
    type: 'video',
    title: 'Git Branching Merge Rebase and Conflict Resolution Tutorial',
    url: 'TODO_GIT_INTERMEDIATE_VIDEO_URL',
    provider: 'YouTube',
    tags: ['git', 'branching', 'merge', 'rebase'],
    source: 'curated',
    score: 89,
  },
  {
    skillName: 'Docker',
    targetRole: 'Software Developer',
    level: 'intermediate',
    language: 'en',
    type: 'video',
    title: 'Docker Compose Volumes and Networks Tutorial',
    url: 'TODO_DOCKER_INTERMEDIATE_VIDEO_URL',
    provider: 'YouTube',
    tags: ['docker', 'docker-compose', 'volumes', 'networks'],
    source: 'curated',
    score: 89,
  },
  {
    skillName: 'TypeScript',
    targetRole: 'Frontend Developer',
    level: 'beginner',
    language: 'en',
    type: 'video',
    title: 'TypeScript Tutorial for Beginners',
    url: 'TODO_TYPESCRIPT_BEGINNER_VIDEO_URL',
    provider: 'YouTube',
    tags: ['typescript', 'javascript', 'frontend', 'typing'],
    source: 'curated',
    score: 94,
  },
  {
    skillName: 'TypeScript',
    targetRole: 'Frontend Developer',
    level: 'intermediate',
    language: 'en',
    type: 'video',
    title: 'TypeScript Intermediate Practical Guide',
    url: 'TODO_TYPESCRIPT_INTERMEDIATE_VIDEO_URL',
    provider: 'YouTube',
    tags: ['typescript', 'generics', 'interfaces', 'advanced-types'],
    source: 'curated',
    score: 90,
  },
  {
    skillName: 'React Hooks',
    targetRole: 'Frontend Developer',
    level: 'beginner',
    language: 'en',
    type: 'video',
    title: 'React Hooks Tutorial for Beginners',
    url: 'TODO_REACT_HOOKS_BEGINNER_VIDEO_URL',
    provider: 'YouTube',
    tags: ['react', 'hooks', 'frontend', 'state'],
    source: 'curated',
    score: 92,
  },
  {
    skillName: 'React Router',
    targetRole: 'Frontend Developer',
    level: 'beginner',
    language: 'en',
    type: 'video',
    title: 'React Router Tutorial for Beginners',
    url: 'TODO_REACT_ROUTER_BEGINNER_VIDEO_URL',
    provider: 'YouTube',
    tags: ['react-router', 'routing', 'react', 'frontend'],
    source: 'curated',
    score: 91,
  },
  {
    skillName: 'Tailwind CSS',
    targetRole: 'Frontend Developer',
    level: 'beginner',
    language: 'en',
    type: 'video',
    title: 'Tailwind CSS Tutorial for Beginners',
    url: 'TODO_TAILWIND_CSS_BEGINNER_VIDEO_URL',
    provider: 'YouTube',
    tags: ['tailwind-css', 'css', 'frontend', 'utility-css'],
    source: 'curated',
    score: 92,
  },
  {
    skillName: 'Bootstrap',
    targetRole: 'Frontend Developer',
    level: 'beginner',
    language: 'en',
    type: 'video',
    title: 'Bootstrap Tutorial for Beginners',
    url: 'TODO_BOOTSTRAP_BEGINNER_VIDEO_URL',
    provider: 'YouTube',
    tags: ['bootstrap', 'css', 'frontend', 'ui'],
    source: 'curated',
    score: 90,
  },
  {
    skillName: 'Responsive Design',
    targetRole: 'Frontend Developer',
    level: 'beginner',
    language: 'en',
    type: 'video',
    title: 'Responsive Design Tutorial for Beginners',
    url: 'TODO_RESPONSIVE_DESIGN_BEGINNER_VIDEO_URL',
    provider: 'YouTube',
    tags: ['responsive-design', 'css', 'mobile-first', 'frontend'],
    source: 'curated',
    score: 91,
  },
  {
    skillName: 'API Integration',
    targetRole: 'Frontend Developer',
    level: 'beginner',
    language: 'en',
    type: 'video',
    title: 'API Integration Tutorial for Beginners',
    url: 'TODO_API_INTEGRATION_BEGINNER_VIDEO_URL',
    provider: 'YouTube',
    tags: ['api', 'fetch', 'frontend', 'integration'],
    source: 'curated',
    score: 91,
  },
  {
    skillName: 'API Integration',
    targetRole: 'Frontend Developer',
    level: 'intermediate',
    language: 'en',
    type: 'video',
    title: 'API Integration Intermediate Practical Guide',
    url: 'TODO_API_INTEGRATION_INTERMEDIATE_VIDEO_URL',
    provider: 'YouTube',
    tags: ['api', 'axios', 'error-handling', 'frontend'],
    source: 'curated',
    score: 89,
  },
  {
    skillName: 'Axios',
    targetRole: 'Frontend Developer',
    level: 'beginner',
    language: 'en',
    type: 'video',
    title: 'Axios Tutorial for Beginners',
    url: 'TODO_AXIOS_BEGINNER_VIDEO_URL',
    provider: 'YouTube',
    tags: ['axios', 'api', 'http-client', 'frontend'],
    source: 'curated',
    score: 90,
  },
  {
    skillName: 'Form Handling',
    targetRole: 'Frontend Developer',
    level: 'beginner',
    language: 'en',
    type: 'video',
    title: 'Form Handling Tutorial for Beginners',
    url: 'TODO_FORM_HANDLING_BEGINNER_VIDEO_URL',
    provider: 'YouTube',
    tags: ['forms', 'validation', 'frontend', 'input'],
    source: 'curated',
    score: 90,
  },
  {
    skillName: 'State Management',
    targetRole: 'Frontend Developer',
    level: 'beginner',
    language: 'en',
    type: 'video',
    title: 'State Management Tutorial for Beginners',
    url: 'TODO_STATE_MANAGEMENT_BEGINNER_VIDEO_URL',
    provider: 'YouTube',
    tags: ['state-management', 'frontend', 'react', 'store'],
    source: 'curated',
    score: 90,
  },
  {
    skillName: 'Vite',
    targetRole: 'Frontend Developer',
    level: 'beginner',
    language: 'en',
    type: 'video',
    title: 'Vite Tutorial for Beginners',
    url: 'TODO_VITE_BEGINNER_VIDEO_URL',
    provider: 'YouTube',
    tags: ['vite', 'frontend', 'build-tool', 'react'],
    source: 'curated',
    score: 90,
  },
  {
    skillName: 'REST API',
    targetRole: 'Backend Developer',
    level: 'beginner',
    language: 'en',
    type: 'video',
    title: 'REST API Tutorial for Beginners',
    url: 'TODO_REST_API_BEGINNER_VIDEO_URL',
    provider: 'YouTube',
    tags: ['rest-api', 'backend', 'http', 'api'],
    source: 'curated',
    score: 94,
  },
  {
    skillName: 'REST API',
    targetRole: 'Backend Developer',
    level: 'intermediate',
    language: 'en',
    type: 'video',
    title: 'REST API Intermediate Practical Guide',
    url: 'TODO_REST_API_INTERMEDIATE_VIDEO_URL',
    provider: 'YouTube',
    tags: ['rest-api', 'status-codes', 'pagination', 'api-design'],
    source: 'curated',
    score: 90,
  },
  {
    skillName: 'CRUD',
    targetRole: 'Backend Developer',
    level: 'beginner',
    language: 'en',
    type: 'video',
    title: 'CRUD Tutorial for Beginners',
    url: 'TODO_CRUD_BEGINNER_VIDEO_URL',
    provider: 'YouTube',
    tags: ['crud', 'backend', 'database', 'api'],
    source: 'curated',
    score: 92,
  },
  {
    skillName: 'JWT Authentication',
    targetRole: 'Backend Developer',
    level: 'beginner',
    language: 'en',
    type: 'video',
    title: 'JWT Authentication Tutorial for Beginners',
    url: 'TODO_JWT_AUTHENTICATION_BEGINNER_VIDEO_URL',
    provider: 'YouTube',
    tags: ['jwt', 'authentication', 'backend', 'security'],
    source: 'curated',
    score: 93,
  },
  {
    skillName: 'JWT Authentication',
    targetRole: 'Backend Developer',
    level: 'intermediate',
    language: 'en',
    type: 'video',
    title: 'JWT Authentication Intermediate Practical Guide',
    url: 'TODO_JWT_AUTHENTICATION_INTERMEDIATE_VIDEO_URL',
    provider: 'YouTube',
    tags: ['jwt', 'refresh-token', 'authorization', 'security'],
    source: 'curated',
    score: 90,
  },
  {
    skillName: 'Middleware',
    targetRole: 'Backend Developer',
    level: 'beginner',
    language: 'en',
    type: 'video',
    title: 'Middleware Tutorial for Beginners',
    url: 'TODO_MIDDLEWARE_BEGINNER_VIDEO_URL',
    provider: 'YouTube',
    tags: ['middleware', 'express.js', 'backend', 'request'],
    source: 'curated',
    score: 90,
  },
  {
    skillName: 'Validation',
    targetRole: 'Backend Developer',
    level: 'beginner',
    language: 'en',
    type: 'video',
    title: 'Validation Tutorial for Beginners',
    url: 'TODO_VALIDATION_BEGINNER_VIDEO_URL',
    provider: 'YouTube',
    tags: ['validation', 'backend', 'api', 'request-body'],
    source: 'curated',
    score: 90,
  },
  {
    skillName: 'Error Handling',
    targetRole: 'Backend Developer',
    level: 'beginner',
    language: 'en',
    type: 'video',
    title: 'Error Handling Tutorial for Beginners',
    url: 'TODO_ERROR_HANDLING_BEGINNER_VIDEO_URL',
    provider: 'YouTube',
    tags: ['error-handling', 'backend', 'api', 'express.js'],
    source: 'curated',
    score: 90,
  },
  {
    skillName: 'Environment Variables',
    targetRole: 'Backend Developer',
    level: 'beginner',
    language: 'en',
    type: 'video',
    title: 'Environment Variables Tutorial for Beginners',
    url: 'TODO_ENVIRONMENT_VARIABLES_BEGINNER_VIDEO_URL',
    provider: 'YouTube',
    tags: ['environment-variables', 'dotenv', 'configuration', 'backend'],
    source: 'curated',
    score: 90,
  },
  {
    skillName: 'File Upload',
    targetRole: 'Backend Developer',
    level: 'beginner',
    language: 'en',
    type: 'video',
    title: 'File Upload Tutorial for Beginners',
    url: 'TODO_FILE_UPLOAD_BEGINNER_VIDEO_URL',
    provider: 'YouTube',
    tags: ['file-upload', 'backend', 'multer', 'api'],
    source: 'curated',
    score: 89,
  },
  {
    skillName: 'Swagger',
    targetRole: 'Backend Developer',
    level: 'beginner',
    language: 'en',
    type: 'video',
    title: 'Swagger Tutorial for Beginners',
    url: 'TODO_SWAGGER_BEGINNER_VIDEO_URL',
    provider: 'YouTube',
    tags: ['swagger', 'api-docs', 'openapi', 'backend'],
    source: 'curated',
    score: 89,
  },
  {
    skillName: 'Mongoose',
    targetRole: 'Backend Developer',
    level: 'beginner',
    language: 'en',
    type: 'video',
    title: 'Mongoose Tutorial for Beginners',
    url: 'TODO_MONGOOSE_BEGINNER_VIDEO_URL',
    provider: 'YouTube',
    tags: ['mongoose', 'mongodb', 'backend', 'schema'],
    source: 'curated',
    score: 93,
  },
  {
    skillName: 'Mongoose',
    targetRole: 'Backend Developer',
    level: 'intermediate',
    language: 'en',
    type: 'video',
    title: 'Mongoose Intermediate Practical Guide',
    url: 'TODO_MONGOOSE_INTERMEDIATE_VIDEO_URL',
    provider: 'YouTube',
    tags: ['mongoose', 'populate', 'validation', 'database'],
    source: 'curated',
    score: 90,
  },
  {
    skillName: 'SQL',
    targetRole: 'Backend Developer',
    level: 'beginner',
    language: 'en',
    type: 'video',
    title: 'SQL Tutorial for Beginners',
    url: 'TODO_SQL_BEGINNER_VIDEO_URL',
    provider: 'YouTube',
    tags: ['sql', 'database', 'query', 'backend'],
    source: 'curated',
    score: 93,
  },
  {
    skillName: 'MySQL',
    targetRole: 'Backend Developer',
    level: 'beginner',
    language: 'en',
    type: 'video',
    title: 'MySQL Tutorial for Beginners',
    url: 'TODO_MYSQL_BEGINNER_VIDEO_URL',
    provider: 'YouTube',
    tags: ['mysql', 'sql', 'database', 'backend'],
    source: 'curated',
    score: 91,
  },
  {
    skillName: 'PostgreSQL',
    targetRole: 'Backend Developer',
    level: 'beginner',
    language: 'en',
    type: 'video',
    title: 'PostgreSQL Tutorial for Beginners',
    url: 'TODO_POSTGRESQL_BEGINNER_VIDEO_URL',
    provider: 'YouTube',
    tags: ['postgresql', 'sql', 'database', 'backend'],
    source: 'curated',
    score: 91,
  },
  {
    skillName: 'Database Design',
    targetRole: 'Backend Developer',
    level: 'beginner',
    language: 'en',
    type: 'video',
    title: 'Database Design Tutorial for Beginners',
    url: 'TODO_DATABASE_DESIGN_BEGINNER_VIDEO_URL',
    provider: 'YouTube',
    tags: ['database-design', 'schema', 'relationships', 'backend'],
    source: 'curated',
    score: 92,
  },
  {
    skillName: 'Database Design',
    targetRole: 'Backend Developer',
    level: 'intermediate',
    language: 'en',
    type: 'video',
    title: 'Database Design Intermediate Practical Guide',
    url: 'TODO_DATABASE_DESIGN_INTERMEDIATE_VIDEO_URL',
    provider: 'YouTube',
    tags: ['database-design', 'normalization', 'indexing', 'data-modeling'],
    source: 'curated',
    score: 89,
  },
  {
    skillName: 'Data Modeling',
    targetRole: 'Backend Developer',
    level: 'beginner',
    language: 'en',
    type: 'video',
    title: 'Data Modeling Tutorial for Beginners',
    url: 'TODO_DATA_MODELING_BEGINNER_VIDEO_URL',
    provider: 'YouTube',
    tags: ['data-modeling', 'database', 'schema', 'backend'],
    source: 'curated',
    score: 90,
  },
  {
    skillName: 'MongoDB CRUD',
    targetRole: 'Backend Developer',
    level: 'beginner',
    language: 'en',
    type: 'video',
    title: 'MongoDB CRUD Tutorial for Beginners',
    url: 'TODO_MONGODB_CRUD_BEGINNER_VIDEO_URL',
    provider: 'YouTube',
    tags: ['mongodb', 'crud', 'database', 'backend'],
    source: 'curated',
    score: 91,
  },
  {
    skillName: 'MongoDB Aggregation',
    targetRole: 'Backend Developer',
    level: 'intermediate',
    language: 'en',
    type: 'video',
    title: 'MongoDB Aggregation Intermediate Practical Guide',
    url: 'TODO_MONGODB_AGGREGATION_INTERMEDIATE_VIDEO_URL',
    provider: 'YouTube',
    tags: ['mongodb', 'aggregation', 'pipeline', 'database'],
    source: 'curated',
    score: 89,
  },
  {
    skillName: 'GitHub',
    targetRole: 'Software Developer',
    level: 'beginner',
    language: 'en',
    type: 'video',
    title: 'GitHub Tutorial for Beginners',
    url: 'TODO_GITHUB_BEGINNER_VIDEO_URL',
    provider: 'YouTube',
    tags: ['github', 'git', 'repository', 'collaboration'],
    source: 'curated',
    score: 91,
  },
  {
    skillName: 'Docker Compose',
    targetRole: 'Software Developer',
    level: 'beginner',
    language: 'en',
    type: 'video',
    title: 'Docker Compose Tutorial for Beginners',
    url: 'TODO_DOCKER_COMPOSE_BEGINNER_VIDEO_URL',
    provider: 'YouTube',
    tags: ['docker-compose', 'docker', 'devops', 'containers'],
    source: 'curated',
    score: 90,
  },
  {
    skillName: 'Postman',
    targetRole: 'Software Developer',
    level: 'beginner',
    language: 'en',
    type: 'video',
    title: 'Postman Tutorial for Beginners',
    url: 'TODO_POSTMAN_BEGINNER_VIDEO_URL',
    provider: 'YouTube',
    tags: ['postman', 'api-testing', 'backend', 'tools'],
    source: 'curated',
    score: 91,
  },
  {
    skillName: 'Render Deployment',
    targetRole: 'Software Developer',
    level: 'beginner',
    language: 'en',
    type: 'video',
    title: 'Render Deployment Tutorial for Beginners',
    url: 'TODO_RENDER_DEPLOYMENT_BEGINNER_VIDEO_URL',
    provider: 'YouTube',
    tags: ['render', 'deployment', 'backend', 'hosting'],
    source: 'curated',
    score: 89,
  },
  {
    skillName: 'Vercel Deployment',
    targetRole: 'Frontend Developer',
    level: 'beginner',
    language: 'en',
    type: 'video',
    title: 'Vercel Deployment Tutorial for Beginners',
    url: 'TODO_VERCEL_DEPLOYMENT_BEGINNER_VIDEO_URL',
    provider: 'YouTube',
    tags: ['vercel', 'deployment', 'frontend', 'hosting'],
    source: 'curated',
    score: 89,
  },
  {
    skillName: 'CI/CD Basics',
    targetRole: 'Software Developer',
    level: 'beginner',
    language: 'en',
    type: 'video',
    title: 'CI/CD Basics Tutorial for Beginners',
    url: 'TODO_CI_CD_BASICS_BEGINNER_VIDEO_URL',
    provider: 'YouTube',
    tags: ['ci-cd', 'automation', 'deployment', 'github-actions'],
    source: 'curated',
    score: 89,
  },
  {
    skillName: 'GitHub Actions',
    targetRole: 'Software Developer',
    level: 'beginner',
    language: 'en',
    type: 'video',
    title: 'GitHub Actions Tutorial for Beginners',
    url: 'TODO_GITHUB_ACTIONS_BEGINNER_VIDEO_URL',
    provider: 'YouTube',
    tags: ['github-actions', 'ci-cd', 'automation', 'github'],
    source: 'curated',
    score: 89,
  },
  {
    skillName: 'Jest',
    targetRole: 'Software Developer',
    level: 'beginner',
    language: 'en',
    type: 'video',
    title: 'Jest Tutorial for Beginners',
    url: 'TODO_JEST_BEGINNER_VIDEO_URL',
    provider: 'YouTube',
    tags: ['jest', 'testing', 'javascript', 'unit-testing'],
    source: 'curated',
    score: 90,
  },
  {
    skillName: 'Unit Testing',
    targetRole: 'Software Developer',
    level: 'beginner',
    language: 'en',
    type: 'video',
    title: 'Unit Testing Tutorial for Beginners',
    url: 'TODO_UNIT_TESTING_BEGINNER_VIDEO_URL',
    provider: 'YouTube',
    tags: ['unit-testing', 'testing', 'quality', 'software'],
    source: 'curated',
    score: 90,
  },
  {
    skillName: 'API Testing',
    targetRole: 'Backend Developer',
    level: 'beginner',
    language: 'en',
    type: 'video',
    title: 'API Testing Tutorial for Beginners',
    url: 'TODO_API_TESTING_BEGINNER_VIDEO_URL',
    provider: 'YouTube',
    tags: ['api-testing', 'postman', 'backend', 'quality'],
    source: 'curated',
    score: 90,
  },
  {
    skillName: 'Clean Code',
    targetRole: 'Software Developer',
    level: 'beginner',
    language: 'en',
    type: 'video',
    title: 'Clean Code Tutorial for Beginners',
    url: 'TODO_CLEAN_CODE_BEGINNER_VIDEO_URL',
    provider: 'YouTube',
    tags: ['clean-code', 'software-engineering', 'readability', 'quality'],
    source: 'curated',
    score: 90,
  },
  {
    skillName: 'Clean Code',
    targetRole: 'Software Developer',
    level: 'intermediate',
    language: 'en',
    type: 'video',
    title: 'Clean Code Intermediate Practical Guide',
    url: 'TODO_CLEAN_CODE_INTERMEDIATE_VIDEO_URL',
    provider: 'YouTube',
    tags: ['clean-code', 'refactoring', 'design-principles', 'quality'],
    source: 'curated',
    score: 88,
  },
  {
    skillName: 'Debugging',
    targetRole: 'Software Developer',
    level: 'beginner',
    language: 'en',
    type: 'video',
    title: 'Debugging Tutorial for Beginners',
    url: 'TODO_DEBUGGING_BEGINNER_VIDEO_URL',
    provider: 'YouTube',
    tags: ['debugging', 'developer-tools', 'bug-fixing', 'software'],
    source: 'curated',
    score: 90,
  },
  {
    skillName: 'React Native',
    targetRole: 'Mobile Developer',
    level: 'beginner',
    language: 'en',
    type: 'video',
    title: 'React Native Tutorial for Beginners',
    url: 'TODO_REACT_NATIVE_BEGINNER_VIDEO_URL',
    provider: 'YouTube',
    tags: ['react-native', 'mobile', 'javascript', 'app'],
    source: 'curated',
    score: 91,
  },
  {
    skillName: 'Expo',
    targetRole: 'Mobile Developer',
    level: 'beginner',
    language: 'en',
    type: 'video',
    title: 'Expo Tutorial for Beginners',
    url: 'TODO_EXPO_BEGINNER_VIDEO_URL',
    provider: 'YouTube',
    tags: ['expo', 'react-native', 'mobile', 'app'],
    source: 'curated',
    score: 90,
  },
  {
    skillName: 'Gemini API',
    targetRole: 'AI Developer',
    level: 'beginner',
    language: 'en',
    type: 'video',
    title: 'Gemini API Tutorial for Beginners',
    url: 'TODO_GEMINI_API_BEGINNER_VIDEO_URL',
    provider: 'YouTube',
    tags: ['gemini-api', 'ai', 'llm', 'api'],
    source: 'curated',
    score: 90,
  },
  {
    skillName: 'Prompt Engineering',
    targetRole: 'AI Developer',
    level: 'beginner',
    language: 'en',
    type: 'video',
    title: 'Prompt Engineering Tutorial for Beginners',
    url: 'TODO_PROMPT_ENGINEERING_BEGINNER_VIDEO_URL',
    provider: 'YouTube',
    tags: ['prompt-engineering', 'ai', 'llm', 'chatbot'],
    source: 'curated',
    score: 90,
  },
  {
    skillName: 'Chatbot',
    targetRole: 'AI Developer',
    level: 'beginner',
    language: 'en',
    type: 'video',
    title: 'Chatbot Tutorial for Beginners',
    url: 'TODO_CHATBOT_BEGINNER_VIDEO_URL',
    provider: 'YouTube',
    tags: ['chatbot', 'ai', 'llm', 'conversation'],
    source: 'curated',
    score: 90,
  },
];
