// Legacy weighted role vectors kept for backward compatibility with older
// non-Dev2Vec helpers. Dev2Vec phase 5/6/7 paths and GET /api/roles/catalog
// must use src/constants/dev2vecCatalog.js instead.
const skill = (name, weight, minScore, importance) => ({
  skill: name,
  canonicalSkillName: name,
  weight,
  minScore,
  importance,
});

const ROLE_SKILL_VECTORS = [
  {
    roleId: 'backend-developer',
    roleName: 'Backend Developer',
    description: 'Xây dựng API, xử lý business logic, database và authentication.',
    category: 'Software Development',
    level: 'entry',
    requiredSkills: [
      skill('JavaScript', 0.7, 0.4, 'important'),
      skill('Node.js', 0.9, 0.5, 'required'),
      skill('Express.js', 0.9, 0.5, 'required'),
      skill('REST API', 0.9, 0.5, 'required'),
      skill('MongoDB', 0.7, 0.4, 'important'),
      skill('Mongoose', 0.7, 0.4, 'important'),
      skill('Authentication', 0.8, 0.5, 'required'),
      skill('JWT Authentication', 0.8, 0.5, 'important'),
      skill('Environment Variables', 0.6, 0.4, 'important'),
      skill('API Security', 0.7, 0.4, 'important'),
      skill('Testing', 0.8, 0.4, 'required'),
      skill('API Testing', 0.7, 0.4, 'important'),
      skill('Clean Code', 0.7, 0.4, 'important'),
    ],
    optionalSkills: [
      skill('Docker', 0.5, 0.4, 'optional'),
      skill('Docker Compose', 0.4, 0.4, 'optional'),
      skill('Swagger', 0.4, 0.3, 'optional'),
      skill('CI/CD', 0.4, 0.3, 'optional'),
      skill('GitHub Actions', 0.3, 0.3, 'optional'),
    ],
  },
  {
    roleId: 'frontend-developer',
    roleName: 'Frontend Developer',
    description: 'Xây dựng giao diện web, quản lý state và tích hợp backend API.',
    category: 'Software Development',
    level: 'entry',
    requiredSkills: [
      skill('JavaScript', 0.9, 0.5, 'required'),
      skill('HTML', 0.9, 0.5, 'required'),
      skill('CSS', 0.9, 0.5, 'required'),
      skill('React', 0.9, 0.5, 'required'),
      skill('REST API', 0.5, 0.4, 'important'),
      skill('API Integration', 0.8, 0.5, 'required'),
      skill('Axios', 0.6, 0.4, 'important'),
      skill('State Management', 0.7, 0.4, 'important'),
      skill('Responsive Design', 0.7, 0.4, 'important'),
      skill('Clean Code', 0.7, 0.4, 'important'),
      skill('Testing', 0.7, 0.4, 'important'),
    ],
    optionalSkills: [
      skill('TypeScript', 0.5, 0.4, 'optional'),
      skill('Tailwind CSS', 0.4, 0.3, 'optional'),
      skill('Vite', 0.3, 0.3, 'optional'),
      skill('React Router', 0.4, 0.3, 'optional'),
    ],
  },
  {
    roleId: 'fullstack-developer',
    roleName: 'Fullstack Developer',
    description: 'Phát triển đồng thời frontend, backend API và lớp dữ liệu.',
    category: 'Software Development',
    level: 'entry',
    requiredSkills: [
      skill('JavaScript', 0.9, 0.5, 'required'),
      skill('Node.js', 0.8, 0.5, 'required'),
      skill('Express.js', 0.8, 0.5, 'required'),
      skill('React', 0.8, 0.5, 'required'),
      skill('REST API', 0.9, 0.5, 'required'),
      skill('MongoDB', 0.7, 0.4, 'important'),
      skill('Mongoose', 0.6, 0.4, 'important'),
      skill('Authentication', 0.7, 0.4, 'important'),
      skill('JWT Authentication', 0.6, 0.4, 'important'),
      skill('API Integration', 0.7, 0.4, 'important'),
      skill('Environment Variables', 0.5, 0.4, 'important'),
      skill('Testing', 0.7, 0.4, 'important'),
      skill('Clean Code', 0.7, 0.4, 'important'),
    ],
    optionalSkills: [
      skill('Docker', 0.5, 0.4, 'optional'),
      skill('Swagger', 0.4, 0.3, 'optional'),
      skill('CI/CD', 0.4, 0.3, 'optional'),
      skill('TypeScript', 0.4, 0.4, 'optional'),
    ],
  },
  {
    roleId: 'devops-engineer',
    roleName: 'DevOps Engineer',
    description: 'Tự động hóa build, kiểm thử, triển khai và quản lý môi trường chạy ứng dụng.',
    category: 'Infrastructure & Operations',
    level: 'entry',
    requiredSkills: [
      skill('Docker', 0.9, 0.5, 'required'),
      skill('Docker Compose', 0.8, 0.5, 'required'),
      skill('CI/CD', 0.9, 0.5, 'required'),
      skill('GitHub Actions', 0.8, 0.4, 'required'),
      skill('Environment Variables', 0.7, 0.4, 'important'),
      skill('Git', 0.7, 0.4, 'important'),
      skill('GitHub', 0.6, 0.4, 'important'),
      skill('Testing', 0.6, 0.4, 'important'),
      skill('Clean Code', 0.5, 0.4, 'important'),
    ],
    optionalSkills: [
      skill('Render Deployment', 0.4, 0.3, 'optional'),
      skill('Vercel Deployment', 0.4, 0.3, 'optional'),
      skill('API Testing', 0.3, 0.3, 'optional'),
    ],
  },
  {
    roleId: 'mobile-developer',
    roleName: 'Mobile Developer',
    description: 'Xây dựng ứng dụng di động và tích hợp API bằng React Native.',
    category: 'Software Development',
    level: 'entry',
    requiredSkills: [
      skill('React Native', 0.9, 0.5, 'required'),
      skill('JavaScript', 0.8, 0.5, 'required'),
      skill('API Integration', 0.8, 0.4, 'required'),
      skill('Authentication', 0.6, 0.4, 'important'),
      skill('State Management', 0.7, 0.4, 'important'),
      skill('Clean Code', 0.7, 0.4, 'important'),
      skill('Testing', 0.7, 0.4, 'important'),
    ],
    optionalSkills: [
      skill('Expo', 0.6, 0.4, 'optional'),
      skill('TypeScript', 0.5, 0.4, 'optional'),
      skill('Axios', 0.4, 0.3, 'optional'),
    ],
  },
  {
    roleId: 'ai-engineer',
    roleName: 'AI Engineer',
    description: 'Tích hợp mô hình ngôn ngữ và xây dựng tính năng AI trong ứng dụng.',
    category: 'Artificial Intelligence',
    level: 'entry',
    requiredSkills: [
      skill('LLM API Integration', 0.9, 0.5, 'required'),
      skill('Prompt Engineering', 0.8, 0.5, 'required'),
      skill('API Integration', 0.7, 0.4, 'important'),
      skill('Backend Development', 0.6, 0.4, 'important'),
      skill('REST API', 0.6, 0.4, 'important'),
      skill('Clean Code', 0.7, 0.4, 'important'),
      skill('Testing', 0.7, 0.4, 'important'),
    ],
    optionalSkills: [
      skill('Gemini API', 0.6, 0.4, 'optional'),
      skill('OpenAI API', 0.6, 0.4, 'optional'),
      skill('Chatbot', 0.5, 0.4, 'optional'),
      skill('Node.js', 0.4, 0.3, 'optional'),
    ],
  },
];

module.exports = {
  ROLE_SKILL_VECTORS,
};
